"""initial schema

Revision ID: a84c266ff0fd
Revises:
Create Date: 2026-09-06

NOTE: hand-written, not autogenerated. The Supabase Postgres host in .env
(db.wgmvdttojmmjyesfmubx.supabase.co) was not resolvable/reachable from this
environment (DNS lookup failure), so `alembic revision --autogenerate` could not
run against the live database. This migration was written to mirror
app/models/*.py exactly (columns, enums, FKs, unique constraints, indexes).
It has NOT been executed against the real database yet — run
`alembic upgrade head` once connectivity to the Supabase instance is available,
and sanity-check the result with `alembic current` / `\\dt` before relying on it.
"""
from alembic import op
import sqlalchemy as sa

from app.core.types import GUID

# revision identifiers, used by Alembic.
revision = "a84c266ff0fd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("STUDENT", "PROFESSOR", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "student_profiles",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("user_id", GUID(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("roll_number", sa.String(length=50), nullable=False),
        sa.Column("program", sa.String(length=255), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.UniqueConstraint("user_id", name="uq_student_profiles_user_id"),
        sa.UniqueConstraint("roll_number", name="uq_student_profiles_roll_number"),
    )

    op.create_table(
        "professor_profiles",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("user_id", GUID(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.UniqueConstraint("user_id", name="uq_professor_profiles_user_id"),
    )

    op.create_table(
        "subjects",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False, server_default="3"),
        sa.UniqueConstraint("code", name="uq_subjects_code"),
    )

    op.create_table(
        "class_divisions",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("subject_id", GUID(), sa.ForeignKey("subjects.id"), nullable=False),
        sa.Column("professor_id", GUID(), sa.ForeignKey("professor_profiles.id"), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("room", sa.String(length=50), nullable=True),
        sa.UniqueConstraint("subject_id", "name", name="uq_subject_division_name"),
    )

    op.create_table(
        "enrollments",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("student_id", GUID(), sa.ForeignKey("student_profiles.id"), nullable=False),
        sa.Column("class_division_id", GUID(), sa.ForeignKey("class_divisions.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("student_id", "class_division_id", name="uq_student_division"),
    )

    op.create_table(
        "lectures",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("class_division_id", GUID(), sa.ForeignKey("class_divisions.id"), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("room", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "attendance_sessions",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("lecture_id", GUID(), sa.ForeignKey("lectures.id"), nullable=False),
        sa.Column("professor_id", GUID(), sa.ForeignKey("professor_profiles.id"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CLOSED", name="session_status"),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "attendance_tokens",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("session_id", GUID(), sa.ForeignKey("attendance_sessions.id"), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.String(length=128), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("consumed_by", GUID(), sa.ForeignKey("student_profiles.id"), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("nonce", name="uq_attendance_tokens_nonce"),
    )

    op.create_table(
        "attendance_records",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("student_id", GUID(), sa.ForeignKey("student_profiles.id"), nullable=False),
        sa.Column("lecture_id", GUID(), sa.ForeignKey("lectures.id"), nullable=False),
        sa.Column("session_id", GUID(), sa.ForeignKey("attendance_sessions.id"), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PRESENT", "ABSENT", "LATE", "MANUAL", "SUSPICIOUS", name="attendance_status"),
            nullable=False,
        ),
        sa.Column("method", sa.Enum("QR", "MANUAL", name="attendance_method"), nullable=False),
        sa.Column("marked_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("student_id", "lecture_id", name="uq_student_lecture"),
    )

    op.create_table(
        "manual_attendance",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("attendance_record_id", GUID(), sa.ForeignKey("attendance_records.id"), nullable=False),
        sa.Column("professor_id", GUID(), sa.ForeignKey("professor_profiles.id"), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("previous_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "device_sessions",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("user_id", GUID(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("login_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("logout_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "LOGGED_OUT", "REVOKED", name="device_session_status"),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.UniqueConstraint("session_id", name="uq_device_sessions_session_id"),
    )

    op.create_table(
        "cooldowns",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("student_id", GUID(), sa.ForeignKey("student_profiles.id"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False, server_default="manual_logout"),
    )

    op.create_table(
        "security_events",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("user_id", GUID(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="security_event_severity"),
            server_default="LOW",
        ),
        sa.Column("event_metadata", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column(
            "status",
            sa.Enum("OPEN", "FLAGGED", "DISMISSED", name="security_event_status"),
            server_default="OPEN",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "anomaly_scores",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("student_id", GUID(), sa.ForeignKey("student_profiles.id"), nullable=False),
        sa.Column("score", sa.Numeric(5, 2), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("method", sa.String(length=20), nullable=False, server_default="rule_based"),
        sa.Column("computed_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("anomaly_scores")
    op.drop_table("security_events")
    op.drop_table("cooldowns")
    op.drop_table("device_sessions")
    op.drop_table("manual_attendance")
    op.drop_table("attendance_records")
    op.drop_table("attendance_tokens")
    op.drop_table("attendance_sessions")
    op.drop_table("lectures")
    op.drop_table("enrollments")
    op.drop_table("class_divisions")
    op.drop_table("subjects")
    op.drop_table("professor_profiles")
    op.drop_table("student_profiles")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")

    for enum_name in (
        "user_role",
        "session_status",
        "attendance_status",
        "attendance_method",
        "device_session_status",
        "security_event_severity",
        "security_event_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
